CREATE OR REPLACE TRIGGER USED_ROOMS_CHECK
BEFORE INSERT OR UPDATE
ON USED_ROOMS
FOR EACH ROW
BEGIN
	IF UPPER(:NEW.DAY) NOT IN('MONDAY', 'TUESDAY', 'WEDNESDAY',
	'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY') THEN
		RAISE_APPLICATION_ERROR(-20001,'INVALID DAY');
	ELSIF :NEW.TIME_SLOT NOT IN('8-9 AM', '9-10 AM', '10-11 AM',
	'11-12 PM', '12-1 PM', '1-2 PM', '2-3 PM', '3-4 PM', '4-5 PM',
	'5-6 PM', '6-7 PM') THEN
		RAISE_APPLICATION_ERROR(-20002,'INVALID TIME SLOT');
	ELSIF :NEW.IS_AVAILABLE NOT IN (0, 1) THEN
		RAISE_APPLICATION_ERROR(-20003,'INVALID AVAILIBILITY');
	END IF;
END;
/

CREATE OR REPLACE TRIGGER FACULTY_CHECK
BEFORE INSERT OR UPDATE
ON FACULTY
FOR EACH ROW
BEGIN
	IF LENGTH(:NEW.PASSWORD) < 8 THEN
		RAISE_APPLICATION_ERROR(-20004,'PASSWORD TOO SHORT');
	END IF;
END;
/

CREATE OR REPLACE TRIGGER BOOKED_ROOMS_CHECK
BEFORE INSERT OR UPDATE
ON BOOKED_ROOMS
FOR EACH ROW
BEGIN
	IF :NEW.DATE_OF_BOOKING < SYSDATE THEN
		RAISE_APPLICATION_ERROR(-20005,'CANNOT BOOK ROOMS IN PAST');
	ELSIF :NEW.TIME_SLOT NOT IN('8-9 AM', '9-10 AM', '10-11 AM', 
	'11-12 PM', '12-1 PM', '1-2 PM', '2-3 PM', '3-4 PM', '4-5 PM',
	'5-6 PM', '6-7 PM') THEN
		RAISE_APPLICATION_ERROR(-20002,'INVALID TIME SLOT');
	END IF;
END;
/