CREATE TABLE USED_ROOMS(
	DAY VARCHAR(10),
	TIME_SLOT VARCHAR(10),
	ROOM_NAME VARCHAR(10),
	IS_AVAILABLE NUMBER(1),
	CONSTRAINT USED_ROOMS_PK PRIMARY KEY (DAY, TIME_SLOT, ROOM_NAME)
);

CREATE TABLE DEPARTMENTS(
	DEPT_NO NUMBER(5),
	DEPARTMENT_NAME VARCHAR(40),
	CONSTRAINT DEPARTMENTS_PK PRIMARY KEY(DEPT_NO)
);

CREATE TABLE FACULTY(
	USERNAME VARCHAR(10),
	EMAIL_ID VARCHAR(30),
	PASSWORD VARCHAR(30),
	DEPT_NO NUMBER(5),
	NAME VARCHAR(30),
	CONSTRAINT EMPLOYEES_PK PRIMARY KEY(USERNAME),
	CONSTRAINT EMPLOYEES_FK FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENTS(DEPT_NO)
);

CREATE TABLE BOOKED_ROOMS(
	DATE_OF_BOOKING DATE,
	TIME_SLOT VARCHAR(10),
	ROOM_NAME VARCHAR(10),
	USERNAME VARCHAR(10),
	CONSTRAINT BOOKED_ROOMS_PK PRIMARY KEY(DATE_OF_BOOKING,TIME_SLOT,ROOM_NAME),
	CONSTRAINT BOOKED_ROOMS_FK FOREIGN KEY(USERNAME) REFERENCES FACULTY(USERNAME)
);				