INSERT INTO DEPARTMENTS VALUES(10,'COMPUTER SCIENCE AND ENGINEERING');
INSERT INTO DEPARTMENTS VALUES(11,'ELECTRONICS AND COMMUNICATION ENGINEERING');
INSERT INTO DEPARTMENTS VALUES(12,'MECHANICAL ENGINEERING');
INSERT INTO DEPARTMENTS VALUES(13,'ELECTRICAL AND INSTRUMENTATION ENGINEERING');