CREATE OR REPLACE TRIGGER DEPARTMENTS_INSERT
AFTER INSERT
ON DEPARTMENTS
FOR EACH ROW
BEGIN
	DBMS_OUTPUT.PUT_LINE('DEPARTMENT ADDED SUCCESSFULLY');
END;
/

CREATE OR REPLACE TRIGGER BOOKED_ROOMS_INSERT
AFTER INSERT
ON BOOKED_ROOMS
FOR EACH ROW
BEGIN
	DBMS_OUTPUT.PUT_LINE('ROOM BOOKED SUCCESSFULLY');
END;
/

CREATE OR REPLACE TRIGGER FACULTY_INSERT
AFTER INSERT
ON FACULTY
FOR EACH ROW
BEGIN
	DBMS_OUTPUT.PUT_LINE('FACULTY ADDED SUCCESSFULLY');
END;
/